### ISSUE TITLE
Typo on README example

### ISSUE THREAD

**Issue by jonboiser** [albertosantini/node-opencpu#2]
Thanks for putting this out there on npm. I think that there might be a typo in the readme. In the callback for `opencpu.rCall`, the JSON `data` being returned is an array of objects, so the proper syntax is:

```
opencpu.rCall("/library/datasets/R/mtcars/json", {}, function (err, data) {
    if (!err) {
        // console.log(data.mpg[0] + data.mpg[1]); // => 42
        console.log(data[0].mpg + data[1].mpg); // => 42
    } else {
        console.log("opencpu call failed.");
    }
});
```

Before, the index came after `mpg` (e.g. `data.mpg[0]`).

**Comment by albertosantini** [comment]
Thanks for the feedback.

Fixed. :) 
(Luckly `ex1.js` is correct)

**Comment by jonboiser** [comment]
Thanks! Another thing is that, I initially downloaded this off npm, thinking it was tied to the official [JavaScript client](https://www.opencpu.org/jslib.html). The API for that client has more features (includes wrappers for transferring code and graphs). I think there might be some value in having something for OpenCPU like this on npm, but I'm not sure if the maintainers of OpenCPU have already pushed a module or are interested in pushing one to npm.

**Comment by albertosantini** [comment]
Contributions are well accepted and `node-opencpu` is focused on server side. :)

For another solution (self promoting disclaimer) you may give a look at `rio`: https://github.com/albertosantini/node-rio
