### ISSUE TITLE
Any advice for an api in opencpu like someFunction(...      , Xconti = c("x2")  ,   ...)?

### ISSUE THREAD

**Issue by followtheart** [albertosantini/node-opencpu#3]
> someFunction(...      , Xconti = c('x2')  ,   ...)

In this situation,the parameter is not a string nor number,
while it seems  parameters always convert to strings before post to opencpu-server in node-opencpu.
Any advice to avoid the convert from 
> c('x2')        -->work
to 
> "c('x2')"     -->not work

**Comment by albertosantini** [comment]
My two cents.

You may try to deserialize the string in someFunction with the R package `RJSONIO` or `jsonlite`.
