### ISSUE TITLE
Support for sessions

### ISSUE THREAD

**Issue by neverfox** [albertosantini/node-opencpu#4]
Any plans to support this in the API?

**Comment by albertosantini** [comment]
Thanks for the request.
Added in master.

Test: https://github.com/albertosantini/node-opencpu/blob/master/test/raw-test.js#L43

If it is ok, I publish a new version.
Otherwise, feel free to describe your use case or your changes.

If you wish to contribute, you are welcome. :)

**Comment by albertosantini** [comment]
Published 0.6.0.

Feel free to open a new issue depending on your mileage.
