### ISSUE TITLE
upload files

### ISSUE THREAD

**Issue by pabloolivera** [albertosantini/node-opencpu#5]
It's posible? I try...

opencpu.rCall("../library/base/R/load", {file: 'C:/projects/opencpu/myCSV/mydata.rda', envir: 'parent.frame()', verbose: 'FALSE'}, function (err, dataR) {
            if (!err) {...

but dont work. Please, help me.

**Comment by albertosantini** [comment]
Thanks for the feedback.

`It doesn't work` usually doesn't mean anything.

The main troubleshooting element is  the `opencpu` call.
What did you try and what is the difference between `opencpu` call you tried and `node-opencpu` you posted above?

You may give a look at api opencpu docs, you know, the projects and the authors are different.
I think you may give a look at `Input, Output: Data and Formats`, but that is matter of `opencpu` project.

In the meantime, this is an invalid issue.

**Comment by pabloolivera** [comment]
Then... do i need use curl to do it? There are not other way?

**Comment by albertosantini** [comment]
Firstly you need to use an `opencpu` api.
You can test it with `curl` as you said.

Then you can port that endpoint to `node-opencpu`.

**Comment by pabloolivera** [comment]
Ok, thank you so much.
