### ISSUE TITLE
opencpu server question

### ISSUE THREAD

**Issue by guillaumechaumet** [albertosantini/node-opencpu#6]
Dear Alberto,
It's more a question than an issue: 
I used the 'server' version of opencpu since 1 year and I'm now curious about nodejs.
You proposed an Local Single-User Server example if I'm not mistaken.
Do you achieve to build an API with nodejs and opencpu ?
If Yes, do you have a shareable example ?

**Comment by albertosantini** [comment]
Thanks for the question.

`node-opencpu` is an OpenCPU client based on Node.js.

Main aim is providing a client for Node.js apps.
Node.js apps can connect to an OpenCpu server via `node-opencpu`.

Hope I explained better `node-opencpu` domain.

**Comment by guillaumechaumet** [comment]
Thanks for the reply
