### ISSUE TITLE
Question - Can this client be used in Angular?

### ISSUE THREAD

**Issue by nelusan** [albertosantini/node-opencpu#9]
Hello, can this client be used in Angular? I am trying to create an R->Angular pipeline for displaying data and models. Thanks in advance.

**Comment by albertosantini** [comment]
You can use opencpu, but I highlight also this project of mine: https://github.com/albertosantini/node-rio.

Anyway it would not be best practice to connect directly the frontend with a backend service like a number crunching layer. It would be better to use a facade patter for your frontend and behind the scene using one of these projects.

Hope the helps.
